#INJECT at home workaround for BPM replacing stuff
# TODO add fetch files
import regex
import pdxpy
import json
#import request
# Variables
message = "This file was generated by update_ultra_p_updater.py\n"
ultra_d_location = ""

radlibs_mil_ideology_effect = [
    pdxpy.PdxUtil.if_statement(
        {"OR":['bpm_country_is_in_new_world = yes','this ?= c:GBR']},
        "ig:ig_radicals ?= { add_ideology = ideology_mil_patriotic_liberal }"
    ),
    {"else":["ig:ig_radicals ?= { add_ideology = ideology_mil_mass_army }"]}
]

# with open("bpm_leader_ideologies.txt",'r') as f:
#     lines = f.read()

# def matcher (key):
#     template = regex.compile(fr'{key} =\s*(\{{(?:[^{{}}]++|(?1))*\}})')
#     match = regex.search(template,lines).group()
#     # if match:
#     #     match = match.replace( str1,str2, 1)
#     #     return(match)

# INJECTING in leader ideology using this stupid thing
# with open("BPM and Ultra politics compatch/common/ideologies/zzzzz_bpm_ultra_p_leader_ideologies.txt","w+", encoding = "utf-8-sig") as f:
#     for key,value in template.items():
#         # template = regex.compile(fr'{key} =\s*(\{{(?:[^{{}}]++|(?1))*\}})')
#         # match = regex.search(template,lines).group()
#         matcher(key)
#         if match:
#             match = match.replace(
#                 "interest_group_leader_trigger = {",
#                 f"{pdxpy.PdxObject(value)}\n\tinterest_group_leader_trigger = {{", 1
#             )
#             f.write(match +str('\n'))
#         # f.write(
#         #     matcher(
#         #         key,
#         #         "interest_group_leader_trigger = {",
#         #         f"{pdxpy.PdxObject(value)}\n\tinterest_group_leader_trigger = {{"
#         #     ) + str("\n")
#         # )

#INJECTING in liberals effect